apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-app-virtualservice
spec:
  gateways:
  - my-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        exact: /status
      method:
        exact: GET
    route:
    - destination:
        host: my-app-service
        port:
          number: 80
  - match:
    - uri:
        exact: /metrics
      method:
        exact: GET
    route:
    - destination:
        host: my-app-service
        port:
          number: 80
  - match:
    - uri:
        exact: /logs
      method:
        exact: GET
    route:
    - destination:
        host: my-app-service
        port:
          number: 80
  - match:
    - uri:
        exact: /log
      method:
        exact: POST
    fault:
      delay:
        fixedDelay: 2s
        percentage:
          value: 100
    retries:
      attempts: 2
      perTryTimeout: 1s
      retryOn: deadline-exceeded
    route:
    - destination:
        host: my-app-service
        port:
          number: 80
  - match:
    - uri:
        exact: /
      method:
        exact: GET
    route:
    - destination:
        host: my-app-service
        port:
          number: 80

  - fault:
      abort:
        httpStatus: 404
        percentage:
          value: 100
    route:    
    - destination:
        host: my-app-service
        port:
          number: 80
